# Gateway API v__GATEWAY_API_VERSION__ — Standard channel CRDs
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v__GATEWAY_API_VERSION__/standard-install.yaml
