---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - module.otterscale.io
  resources:
  - modules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - module.otterscale.io
  resources:
  - modules/finalizers
  verbs:
  - update
- apiGroups:
  - module.otterscale.io
  resources:
  - modules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - module.otterscale.io
  resources:
  - moduletemplates
  verbs:
  - get
  - list
  - watch
