# KubeVirt deployment — remote resources for FluxCD Kustomization
# Prerequisite: Deploy CDI first
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v__KUBEVIRT_VERSION__/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v__KUBEVIRT_VERSION__/kubevirt-cr.yaml
